### ISSUE TITLE
Error on migrate

### ISSUE THREAD

**Issue by clairton** [duke-libraries/ddr-antivirus#29]
Hi!
have error when run 'rake db:migrate':

``` ruby
rake aborted!
SyntaxError: /usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus/scan_result.rb:9: syntax error, unexpected tLABEL
    def initialize(file_path, output, scanned_at: nil, version: nil)
                                                 ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus/scan_result.rb:9: Can't assign to nil
    def initialize(file_path, output, scanned_at: nil, version: nil)
                                                      ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus/scan_result.rb:35: syntax error, unexpected keyword_end, expecting $end
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus.rb:5:in `require_relative'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr-antivirus.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
```

Can you help-me?

**Comment by coblej** [comment]
@dchandekstark Can you respond to this?  My hunch is that it's a ruby version issue but I'm not sure about that.

**Comment by dchandekstark** [comment]
@clairton We're using Ruby 2.0 Hash syntax, so it doesn't work with Ruby 1.9.3 which you are using.  Are you able to upgrade?  Ruby 1.9.3 has not been supported for some time: https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/.

**Comment by dchandekstark** [comment]
Closing/wontfix - see #30.
